### ISSUE TITLE
Google Chrome Email Already Registered. 

### ISSUE THREAD

**Issue by jerrickhakim** [TomodomoCo/rcp-stripe-elements#2]
Great plugin. I noticed on registration using google chrome does not complete. You get an error that "email address already registered".  The plugin creates an account but does not redirect and log the user in. It works fine on others browsers like safari. I'm running the latest update of restrict content pro and the latest verison on the this plugin. I've tested with stripe checkout and registration works fine. Issue hsappends in sandbox and live mode.  In addtion the stripe charge request is still created. 
<img width="1066" alt="screen shot 2018-01-15 at 10 42 22 pm" src="https://user-images.githubusercontent.com/35478687/34972173-61a83f38-fa45-11e7-9e54-29098d945067.png">

**Comment by chrisvanpatten** [comment]
Interesting… just to confirm, are you using the latest version of RCP?

**Comment by jerrickhakim** [comment]
Hey Chris, Thanks for the reply. I'm on the lastest verison of RCP. Verison 2.9.8 with an active license. After further trouble shooting, I removed all custom template files in child theme and all custom function to not require password twice and to use the user's email as the username. I noticed that the problem was still present. I also uninstalled both plugins and reinstalled and make sure I downloaded the latest verison of the Stripe Elements Plugin.

If you wish on this feel free to follow this link in a Chrome browser to see the problem. 
https://beta.jhakim.com/test/register/

If you choose a paid option registration does not complete, if you choose a free option registration completes fine. This form is currently in test mode. 
Note: Google Chrome on Mac is where the issue occurs. 
FireFox and Safari and good. Mobile Chrome Works.

**Comment by rezzz-dev** [comment]
I'm having the same issue.

Seems that on Chrome, it's not waiting for the response or something from Stripe.

**Comment by chrisvanpatten** [comment]
Thanks for the report! @mcfarlan can you investigate on Monday?

**Comment by rezzz-dev** [comment]
Maybe this has something to do with it? -> https://github.com/stripe/react-stripe-elements/issues/103 ¯\_(ツ)_/¯

**Comment by rezzz-dev** [comment]
I'd be happy to share any information that I have if it's helpful

**Comment by mcfarlan** [comment]
Thanks @rezzz-dev @jerrickhakim - I was able to replicate this and will work on a fix over the next day or two. Will follow up shortly, thanks for letting us know!

**Comment by rezzz-dev** [comment]
Awesome -- thanks @mcfarlan -- appreciate it!

**Comment by mcfarlan** [comment]
We have a fix ready but as it was a tricky one to track down. Do you mind seeing if the fix we've pushed up this morning works well for you @jerrickhakim and @rezzz-dev ? The new branch can be found here…

https://github.com/TomodomoCo/rcp-stripe-elements/tree/fix-chrome-support--issue-2

Once we can confirm your fix we'll get this merged into `master`. Thanks again for filing the issue. Let me know if you need more info

**Comment by rezzz-dev** [comment]
@mcfarlan It's working on my end now -- thanks for the quick fix!

**Comment by jerrickhakim** [comment]
@mcfarlan I just updated the plugin and it is working on my end as well. Thank you.
